-- 회원 간 팔로우. (follower_id)가 (following_id)를 팔로우한다. 쌍당 한 번만.
CREATE TABLE follows (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    following_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_follows_pair UNIQUE (follower_id, following_id),
    CONSTRAINT chk_follows_not_self CHECK (follower_id <> following_id)
);

-- 팔로워 목록(나를 팔로우한 사람) / 팔로잉 목록(내가 팔로우한 사람) 조회용 인덱스
CREATE INDEX idx_follows_following ON follows (following_id, id);
CREATE INDEX idx_follows_follower ON follows (follower_id, id);
