-- 상품 찜. 회원-상품 당 한 번만.
CREATE TABLE wishlists (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_wishlists_product_user UNIQUE (product_id, user_id)
);

-- 한 회원의 찜 목록을 최신순으로 조회하기 위한 인덱스
CREATE INDEX idx_wishlists_user ON wishlists (user_id, id);

-- 찜에 대한 좋아요. 다른 회원이 누군가의 찜을 좋아할 수 있고, 찜-회원 당 한 번만.
CREATE TABLE wishlist_likes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wishlist_id BIGINT      NOT NULL REFERENCES wishlists (id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_wishlist_likes_pair UNIQUE (wishlist_id, user_id)
);

CREATE INDEX idx_wishlist_likes_wishlist ON wishlist_likes (wishlist_id);
