-- 메인 캐러셀/프로모션 큐레이션 카드 (어드민 관리).
-- link_url 이 있으면 그 링크로 이동하고, 없으면 카드 자체 본문(body)을 보여주는
-- 큐레이션 매거진 상세(/magazine/:id)로 이동한다.
CREATE TABLE curation_cards (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kicker        VARCHAR(80),
    title         VARCHAR(200) NOT NULL,
    subtitle      VARCHAR(300),
    body          TEXT,
    image_url     VARCHAR(1024),
    link_url      VARCHAR(1024),
    display_order INT          NOT NULL DEFAULT 0,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- 활성 카드를 정렬 순서대로 조회하기 위한 인덱스
CREATE INDEX idx_curation_cards_active_order ON curation_cards (active, display_order, id);
