-- 주문 (결제는 payment-server). 주문/배송지/항목 스냅샷은 main-server 가 보관한다.
CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status         VARCHAR(20)  NOT NULL DEFAULT 'CREATED',
    recipient_name VARCHAR(100) NOT NULL,
    phone          VARCHAR(40)  NOT NULL,
    postal_code    VARCHAR(20)  NOT NULL,
    address1       VARCHAR(255) NOT NULL,
    address2       VARCHAR(255),
    total_amount   BIGINT       NOT NULL CHECK (total_amount >= 0),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_user ON orders (user_id);

-- 주문 항목 스냅샷. 상품이 이후 변경/삭제돼도 주문 내역이 보존되도록 FK 없이 이름/가격을 박제한다.
CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id   BIGINT       NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    price        BIGINT       NOT NULL CHECK (price >= 0),
    quantity     INTEGER      NOT NULL CHECK (quantity >= 1),
    line_total   BIGINT       NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX idx_order_items_order ON order_items (order_id);
