-- 게시글 연관 상품 (학생증 자랑: 게시글에서 상품으로 바로 이동) (PRD §3.4 확장)
-- 게시글 1 : N 상품. 상품 삭제/게시글 삭제 시 링크도 함께 정리(ON DELETE CASCADE).
CREATE TABLE post_products (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT      NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    product_id BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    sort_order INTEGER     NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_product UNIQUE (post_id, product_id)
);

CREATE INDEX idx_post_products_post ON post_products (post_id);
