-- 매거진: 홈 메인 캐러셀 슬라이드(커버) + 마크다운 본문을 하나로 통합한 엔티티(어드민 발행).
-- published=true 인 매거진만 공개 캐러셀/목록에 노출되고, 슬라이드를 누르면 /magazine/:id
-- 상세에서 마크다운 본문(여러 사진·글, 내부 상품 링크 임베드)을 렌더링한다.
CREATE TABLE magazines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kicker          VARCHAR(80),
    title           VARCHAR(200) NOT NULL,
    subtitle        VARCHAR(300),
    content         TEXT,
    cover_image_url VARCHAR(1024),
    display_order   INT          NOT NULL DEFAULT 0,
    published       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- 발행된 매거진을 정렬 순서대로 조회하기 위한 인덱스
CREATE INDEX idx_magazines_published_order ON magazines (published, display_order, id);
