-- 회원 (PRD §3.1)
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email             VARCHAR(255) NOT NULL UNIQUE,
    nickname          VARCHAR(255) NOT NULL,
    role              VARCHAR(20)  NOT NULL,
    personal_color    VARCHAR(40),
    profile_image_url VARCHAR(1024),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- 회원 선호 스타일 (다대다 태그)
CREATE TABLE user_preferred_styles (
    user_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    style   VARCHAR(100) NOT NULL,
    PRIMARY KEY (user_id, style)
);
