-- 판매 상품 (PRD §3.3)
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id   BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    price       BIGINT       NOT NULL CHECK (price >= 0),
    key_color   VARCHAR(40),
    sub_color   VARCHAR(40),
    image_url   VARCHAR(1024),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_seller ON products (seller_id);
CREATE INDEX idx_products_key_color ON products (key_color);

-- 상품 스타일 태그 (추천 피처 §3.5)
CREATE TABLE product_styles (
    product_id BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    style      VARCHAR(100) NOT NULL,
    PRIMARY KEY (product_id, style)
);
