apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: hakku-prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
