global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    project: hakku

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: main-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: main-server

  - job_name: payment-server
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8083"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: payment-server

  - job_name: storage-server
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8081"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: storage-server

  - job_name: storage-server-spring
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: storage-server-spring

  - job_name: ai-server
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: ai-server
