-- 결제(payment-server) 초기 스키마. main-server 와 같은 hakku DB 를 공유하므로 이 모듈은 별도 Flyway 이력
-- 테이블(flyway_schema_history_payment)과 baseline-on-migrate 로 main-server 마이그레이션과 충돌을 피한다.
-- prod 는 ddl-auto=validate 이므로 컬럼/제약이 JPA 엔티티(Payment, OutboxEvent)와 lockstep 이어야 한다.

-- 결제 애그리거트(도메인 비종속: "참조 R 에 대한 금액 X").
CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    reference_type  VARCHAR(255) NOT NULL,
    reference_id    VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    amount          BIGINT       NOT NULL,
    currency        VARCHAR(255) NOT NULL,
    status          VARCHAR(255) NOT NULL,
    provider        VARCHAR(255) NOT NULL,
    provider_tx_id  VARCHAR(255),
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    -- 멱등 키 UNIQUE: 동시 레이스의 이중 결제 행 생성을 막는 최종 방어선(catch-refetch 의 토대).
    -- ddl-auto=validate 는 UNIQUE 존재를 검사하지 않으므로 반드시 여기서 명시한다.
    CONSTRAINT uq_payments_idempotency_key UNIQUE (idempotency_key)
);

-- 트랜잭셔널 아웃박스: 결제 상태 변경과 같은 트랜잭션에서 기록되고, 릴레이가 PENDING 을 폴링해 Kafka 로 발행한다.
CREATE TABLE payment_outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(255)  NOT NULL,
    aggregate_id   BIGINT        NOT NULL,
    event_type     VARCHAR(255)  NOT NULL,
    payload        VARCHAR(2000) NOT NULL,
    status         VARCHAR(255)  NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    sent_at        TIMESTAMP WITH TIME ZONE
);

-- 릴레이 폴링(findTop100ByStatusOrderByCreatedAtAsc) 가속용 인덱스.
CREATE INDEX idx_payment_outbox_status_created_at ON payment_outbox (status, created_at);
