spring.application.name=storage-server-spring
server.port=${STORAGE_PORT:8082}

storage.base-path=${STORAGE_BASE_PATH:./data/images}

management.endpoints.web.exposure.include=health,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true
