-- =============================================================================
--  학꾸(Hakku) · 통합 스키마 스냅샷 (schema.sql)
-- =============================================================================
--  ⚠ 참고용(REFERENCE-ONLY). 실제 런타임에서는 사용하지 않는다.
--    실 스키마는 Flyway 마이그레이션이 권위 소스다:
--      - main-server/src/main/resources/db/migration/V1~V19
--      - payment-server/src/main/resources/db/migration/V1~V2
--    이 파일은 그 마이그레이션을 모두 적용한 "최종 상태"를 한 파일로 합친 것이다.
--
--  DB        : PostgreSQL 16  ·  데이터베이스명 hakku
--  주의      : main-server 와 payment-server 는 같은 hakku DB 를 공유한다.
--             (Flyway 이력만 flyway_schema_history / flyway_schema_history_payment 로 분리)
--  ENUM      : 네이티브 ENUM 미사용 — 모두 VARCHAR 로 저장하고 도메인 계층에서 검증.
--  PK        : BIGINT GENERATED BY DEFAULT AS IDENTITY
--  시각       : TIMESTAMPTZ DEFAULT now()
--  제외 테이블 : curation_cards (V14 도입 → V18 에서 magazines 로 대체되며 DROP, 최종 스키마에 없음)
--  총 20개 테이블 (FK 의존성 순서로 정렬)
-- =============================================================================


-- ─────────────────────────────────────────────────────────────────────────
--  회원 (users) — V1 + V8 + V9 + V10
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                VARCHAR(255) NOT NULL UNIQUE,
    nickname             VARCHAR(255) NOT NULL,
    password_hash        VARCHAR(255),
    role                 VARCHAR(20)  NOT NULL,                       -- Role: NORMAL | SELLER | ADMIN
    personal_color       VARCHAR(40),                                -- PersonalColorType 16종 (예: TRUE_SUMMER, DEEP_AUTUMN)
    profile_image_url    VARCHAR(1024),
    diagnosis_status     VARCHAR(20)  NOT NULL DEFAULT 'NONE',       -- DiagnosisStatus: NONE | PENDING | COMPLETED
    diagnosis_image_url  VARCHAR(1024),
    onboarding_completed BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- 회원 선호 스타일 (다대다 태그) — V1
CREATE TABLE user_preferred_styles (
    user_id BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    style   VARCHAR(100) NOT NULL,
    PRIMARY KEY (user_id, style)
);

-- 회원 선호 컬러 (다대다 태그) — V9
CREATE TABLE user_preferred_colors (
    user_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    color   VARCHAR(40) NOT NULL,
    PRIMARY KEY (user_id, color)
);


-- ─────────────────────────────────────────────────────────────────────────
--  커뮤니티 게시글 (posts) — V2 + V11
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE posts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id  BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title      VARCHAR(255) NOT NULL,
    content    TEXT         NOT NULL,
    board      VARCHAR(32)  NOT NULL DEFAULT 'GENERAL',  -- PostBoard: GENERAL | STUDENT_ID
    image_url  TEXT,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_posts_author     ON posts (author_id);
CREATE INDEX idx_posts_created_at ON posts (created_at DESC);
CREATE INDEX idx_posts_board_id   ON posts (board, id DESC);

-- 게시글 댓글 — V3
CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT      NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    author_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    content    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_comments_post   ON comments (post_id, id);
CREATE INDEX idx_comments_author ON comments (author_id);

-- 게시글 좋아요 (회원-게시글 당 한 번) — V4
CREATE TABLE post_likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT      NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_likes_post_user UNIQUE (post_id, user_id)
);

CREATE INDEX idx_post_likes_post ON post_likes (post_id);


-- ─────────────────────────────────────────────────────────────────────────
--  판매 상품 (products) — V5 + V9 + V10 + V19
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    price        BIGINT       NOT NULL CHECK (price >= 0),
    key_color    VARCHAR(40),
    sub_color    VARCHAR(40),
    image_url    VARCHAR(1024),
    category     VARCHAR(100),
    purchase_url VARCHAR(2048),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,   -- false 면 공개 목록·검색·추천에서 숨김
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_seller    ON products (seller_id);
CREATE INDEX idx_products_key_color ON products (key_color);
CREATE INDEX idx_products_category  ON products (category);
CREATE INDEX idx_products_active    ON products (active);

-- 상품 스타일 태그 (추천 피처) — V5
CREATE TABLE product_styles (
    product_id BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    style      VARCHAR(100) NOT NULL,
    PRIMARY KEY (product_id, style)
);

-- 상품 컬러 태그 — V9
CREATE TABLE product_colors (
    product_id BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    color      VARCHAR(40) NOT NULL,
    PRIMARY KEY (product_id, color)
);

-- 장바구니 (회원-상품 당 한 행) — V6
CREATE TABLE cart_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    product_id BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    quantity   INTEGER     NOT NULL CHECK (quantity >= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_cart_items_user_product UNIQUE (user_id, product_id)
);

CREATE INDEX idx_cart_items_user ON cart_items (user_id);

-- 상품 리뷰 (회원-상품 당 한 번) — V7
CREATE TABLE reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    author_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    rating     INTEGER     NOT NULL CHECK (rating BETWEEN 1 AND 5),
    content    TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_reviews_product_author UNIQUE (product_id, author_id)
);

CREATE INDEX idx_reviews_product ON reviews (product_id, id);


-- ─────────────────────────────────────────────────────────────────────────
--  소셜 (follows / wishlists) — V12 + V13
-- ─────────────────────────────────────────────────────────────────────────

-- 회원 간 팔로우: (follower_id)가 (following_id)를 팔로우. 쌍당 한 번, 자기 자신 불가.
CREATE TABLE follows (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id  BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    following_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_follows_pair      UNIQUE (follower_id, following_id),
    CONSTRAINT chk_follows_not_self CHECK (follower_id <> following_id)
);

CREATE INDEX idx_follows_following ON follows (following_id, id);
CREATE INDEX idx_follows_follower  ON follows (follower_id, id);

-- 상품 찜 (회원-상품 당 한 번)
CREATE TABLE wishlists (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_wishlists_product_user UNIQUE (product_id, user_id)
);

CREATE INDEX idx_wishlists_user ON wishlists (user_id, id);

-- 찜에 대한 좋아요 (찜-회원 당 한 번)
CREATE TABLE wishlist_likes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wishlist_id BIGINT      NOT NULL REFERENCES wishlists (id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_wishlist_likes_pair UNIQUE (wishlist_id, user_id)
);

CREATE INDEX idx_wishlist_likes_wishlist ON wishlist_likes (wishlist_id);


-- ─────────────────────────────────────────────────────────────────────────
--  주문 (orders / order_items) — V15
--  결제 자체는 payments 테이블이 담당. 주문/배송지/항목 스냅샷은 여기에 보관.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE orders (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status         VARCHAR(20)  NOT NULL DEFAULT 'CREATED',  -- OrderStatus: CREATED | PAID | CANCELLED
    recipient_name VARCHAR(100) NOT NULL,
    phone          VARCHAR(40)  NOT NULL,
    postal_code    VARCHAR(20)  NOT NULL,
    address1       VARCHAR(255) NOT NULL,
    address2       VARCHAR(255),
    total_amount   BIGINT       NOT NULL CHECK (total_amount >= 0),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_user ON orders (user_id);

-- 주문 항목 스냅샷: 상품이 이후 변경/삭제돼도 내역 보존을 위해 product_id 는 FK 없이 이름·가격을 박제한다.
CREATE TABLE order_items (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT       NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id   BIGINT       NOT NULL,                  -- 의도적으로 FK 없음 (스냅샷)
    product_name VARCHAR(255) NOT NULL,
    price        BIGINT       NOT NULL CHECK (price >= 0),
    quantity     INTEGER      NOT NULL CHECK (quantity >= 1),
    line_total   BIGINT       NOT NULL CHECK (line_total >= 0)
);

CREATE INDEX idx_order_items_order ON order_items (order_id);


-- ─────────────────────────────────────────────────────────────────────────
--  게시글 연관 상품 (post_products) — V16
--  학생증 자랑 게시글에서 상품으로 바로 이동. 게시글 1 : N 상품.
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE post_products (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id    BIGINT      NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    product_id BIGINT      NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    sort_order INTEGER     NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_post_product UNIQUE (post_id, product_id)
);

CREATE INDEX idx_post_products_post ON post_products (post_id);


-- ─────────────────────────────────────────────────────────────────────────
--  매거진 (magazines) — V17
--  홈 메인 캐러셀 커버 + 마크다운 본문을 통합한 어드민 발행 엔티티.
--  published=true 만 공개 노출. (V14 curation_cards 를 대체)
-- ─────────────────────────────────────────────────────────────────────────
CREATE TABLE magazines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kicker          VARCHAR(80),
    title           VARCHAR(200) NOT NULL,
    subtitle        VARCHAR(300),
    content         TEXT,
    cover_image_url VARCHAR(1024),
    display_order   INT          NOT NULL DEFAULT 0,
    published       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_magazines_published_order ON magazines (published, display_order, id);


-- ─────────────────────────────────────────────────────────────────────────
--  결제 (payment-server) — V1 + V2 · 같은 hakku DB 공유
-- ─────────────────────────────────────────────────────────────────────────

-- 결제 애그리거트(도메인 비종속: "참조 reference_type/reference_id 에 대한 금액").
-- idempotency_key UNIQUE 가 동시 레이스의 이중 결제를 막는 최종 방어선.
CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,             -- users.id 참조(서비스 분리상 FK 미설정)
    reference_type  VARCHAR(255) NOT NULL,             -- 예: ORDER
    reference_id    VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    amount          BIGINT       NOT NULL,
    currency        VARCHAR(255) NOT NULL,
    status          VARCHAR(255) NOT NULL,             -- PaymentStatus: PENDING | APPROVED | FAILED
    provider        VARCHAR(255) NOT NULL,             -- 예: TOSS
    provider_tx_id  VARCHAR(255),
    version         BIGINT       NOT NULL DEFAULT 0,   -- 낙관적 락
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_payments_idempotency_key UNIQUE (idempotency_key)
);

-- 트랜잭셔널 아웃박스: 결제 상태 변경과 같은 트랜잭션에서 기록 → 릴레이가 PENDING 폴링 후 Kafka 발행.
CREATE TABLE payment_outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(255)  NOT NULL,
    aggregate_id   BIGINT        NOT NULL,
    event_type     VARCHAR(255)  NOT NULL,
    payload        VARCHAR(2000) NOT NULL,
    status         VARCHAR(255)  NOT NULL,             -- OutboxStatus: PENDING | SENT | DEAD
    retry_count    INT           NOT NULL DEFAULT 0,   -- 한계 도달 시 status → DEAD (poison 격리)
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    sent_at        TIMESTAMPTZ
);

CREATE INDEX idx_payment_outbox_status_created_at ON payment_outbox (status, created_at);
